USE [master]
GO

/****** Object:  Database [DriveLicence]    Script Date: 07.02.2022 13:10:46 ******/
CREATE DATABASE [DriveLicence]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DriveLicence', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DriveLicence.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DriveLicence_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DriveLicence_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DriveLicence].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DriveLicence] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DriveLicence] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DriveLicence] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DriveLicence] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DriveLicence] SET ARITHABORT OFF 
GO

ALTER DATABASE [DriveLicence] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DriveLicence] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DriveLicence] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DriveLicence] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DriveLicence] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DriveLicence] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DriveLicence] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DriveLicence] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DriveLicence] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DriveLicence] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DriveLicence] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DriveLicence] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DriveLicence] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DriveLicence] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DriveLicence] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DriveLicence] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DriveLicence] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DriveLicence] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DriveLicence] SET  MULTI_USER 
GO

ALTER DATABASE [DriveLicence] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DriveLicence] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DriveLicence] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DriveLicence] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DriveLicence] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DriveLicence] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DriveLicence] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DriveLicence] SET  READ_WRITE 
GO

